### PR TITLE
Add point about specifying exact output filenames

### PR DESCRIPTION
**Pull request by samuell**
Also suggest making two sub-bullets full bullet points and re-order.

Let me know what you think, or if you want me to split up in more PRs/commits!//

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks for the addition @samuell - its a good and important point!

**Comment by samuell** [comment]
@bgruening np, thanks for putting together the list! It is way more stuff than I had imagined collecting. Great stuff! :slightly_smiling_face:

**Comment by bgruening** [comment]
Your welcome. Its more or less a list of stuff I encountered during the years working on workflows and tool integration's. Maybe its time to publish it or call for review/new ideas ...?

**Comment by samuell** [comment]
> Your welcome. Its more or less a list of stuff I encountered during the years working on workflows and tool integration's. Maybe its time to publish it or call for review/new ideas ...?

Both sound like good ideas to me. Call for review and ideas, especially among folks having worked a lot work worklfows, or with integrating tools, and then publish to spread the awareness :)

**Pull request merged**
